from django.db import models
from django.core.urlresolvers import reverse
from mysite.base import models as bmodels

# Create your models here.
#class Tournament(models.Model):
#    start_date = models.DateTimeField(help_text="Start time of the first game")

class Bracket(models.Model):
    name = models.CharField('Bracket Name',max_length=30)
    #tournament = models.ForeignKey('marchmadness.Tournament')
    official_bracket = models.BooleanField(default=False)
    total_points = models.IntegerField(default=0)

    B1 = models.CharField(max_length=30)
    B2 = models.CharField(max_length=30)
    B3 = models.CharField(max_length=30)
    B4 = models.CharField(max_length=30)
    B5 = models.CharField(max_length=30)
    B6 = models.CharField(max_length=30)
    B7 = models.CharField(max_length=30)
    B8 = models.CharField(max_length=30)
    B9 = models.CharField(max_length=30)
    B10 = models.CharField(max_length=30)
    B11 = models.CharField(max_length=30)
    B12 = models.CharField(max_length=30)
    B13 = models.CharField(max_length=30)
    B14 = models.CharField(max_length=30)
    B15 = models.CharField(max_length=30)
    B16 = models.CharField(max_length=30)
    B17 = models.CharField(max_length=30)
    B18 = models.CharField(max_length=30)
    B19 = models.CharField(max_length=30)
    B20 = models.CharField(max_length=30)
    B21 = models.CharField(max_length=30)
    B22 = models.CharField(max_length=30)
    B23 = models.CharField(max_length=30)
    B24 = models.CharField(max_length=30)
    B25 = models.CharField(max_length=30)
    B26 = models.CharField(max_length=30)
    B27 = models.CharField(max_length=30)
    B28 = models.CharField(max_length=30)
    B29 = models.CharField(max_length=30)
    B30 = models.CharField(max_length=30)
    B31 = models.CharField(max_length=30)
    B32 = models.CharField(max_length=30)
    C1 = models.CharField(max_length=30)
    C2 = models.CharField(max_length=30)
    C3 = models.CharField(max_length=30)
    C4 = models.CharField(max_length=30)
    C5 = models.CharField(max_length=30)
    C6 = models.CharField(max_length=30)
    C7 = models.CharField(max_length=30)
    C8 = models.CharField(max_length=30)
    C9 = models.CharField(max_length=30)
    C10 = models.CharField(max_length=30)
    C11 = models.CharField(max_length=30)
    C12 = models.CharField(max_length=30)
    C13 = models.CharField(max_length=30)
    C14 = models.CharField(max_length=30)
    C15 = models.CharField(max_length=30)
    C16 = models.CharField(max_length=30)
    D1 = models.CharField(max_length=30)
    D2 = models.CharField(max_length=30)
    D3 = models.CharField(max_length=30)
    D4 = models.CharField(max_length=30)
    D5 = models.CharField(max_length=30)
    D6 = models.CharField(max_length=30)
    D7 = models.CharField(max_length=30)
    D8 = models.CharField(max_length=30)
    E1 = models.CharField(max_length=30)
    E2 = models.CharField(max_length=30)
    E3 = models.CharField(max_length=30)
    E4 = models.CharField(max_length=30)
    F1 = models.CharField(max_length=30)
    F2 = models.CharField(max_length=30)
    champ = models.CharField("Champion",max_length=30)


    def get_absolute_url(self):
        return reverse("marchmadness_bracket",kwargs={'bracket_id':self.id})